---
#Install and start Nginx service
- hosts: webservers
  gather_facts: yes
  become: true
  become_method: sudo
  #become_user: root
  tasks:
  - name: Install Nginx
    apt: pkg=nginx state=present
    notify:
    - restart nginx
  - name: Enable Nginx during boot
    service: name=nginx state=started enabled=yes
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

#Install unzip 
- name: Install Unzip
  hosts: webservers
  become: true

  tasks:
    - name: Update Apt cache
      apt: update_cache=yes

    - name: Install Unzip package
      apt:
        name: unzip
        state: present

#Copy HTML5 Files to remote server, unzip them, then restart Nginx service 
- name: Copy and Unzip Files, and Restart Nginx
  hosts: webservers
  become: true

  vars:
    files_to_copy:
      - /path/to/archive.zip

  tasks:
    - name: Copy archive to target server
      copy:
        src: /home/durzo/IacDemo/webtemplate
        dest: /var/www/html
      #with_items: "{{ files_to_copy }}"

    - name: Unzip archive
      unarchive:
        src: /var/www/html/webtemplate
        dest: /var/www/html/
        remote_src: true
        extra_opts: "-q" # optional: quiet mode

    - name: Restart Nginx service
      service:
        name: nginx
        state: restarted
